// This file is generated by Fog.Z.generate_file()

export type APICodeChallengeVerifier = {
  codeChallenge: string;
  verifierEncoded: string;
};

export type APIPagerdutyOauthCode = {
  code: string;
  verifierEncoded: string;
};

