creation_rules:
  - path_regex: dev\.env
    kms: "arn:aws:kms:us-west-1:863191199317:alias/dev-encryption-key-73cc752"
  - path_regex: test\.env
    kms: >-
      arn:aws:kms:us-west-1:863191199317:alias/dev-encryption-key-73cc752,
      arn:aws:kms:us-west-1:863191199317:alias/admin-encryption-key-4d3178b
