#!/usr/bin/env bash

x=$(git diff --name-only --diff-filter d | xargs)

if [[ ${#x} > 0 ]]; then
    npx prettier --write --ignore-unknown --no-error-on-unmatched-pattern $x
else
    echo "No files to format"
fi
