// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    FogbenderSimpleWidget: typeof import("./src/components/FogbenderSimpleWidget"),
    FogbenderProvider: typeof import("./src/components/FogbenderProvider"),
    FogbenderFloatingWidget: typeof import("./src/components/FogbenderFloatingWidget"),
    FogbenderConfig: typeof import("./src/components/FogbenderConfig"),
    FogbenderIsConfigured: typeof import("./src/components/FogbenderIsConfigured")
  }
}

export { };
