creation_rules:
  - path_regex: admin/.*
    kms: "arn:aws:kms:us-west-1:863191199317:alias/admin-encryption-key-4d3178b"
  - path_regex: test/.*
    kms: "arn:aws:kms:us-west-1:863191199317:alias/test-encryption-key-1dfe43e"
  - path_regex: stage/.*
    kms: "arn:aws:kms:us-west-1:863191199317:alias/stage-encryption-key-0183e8e"
  - path_regex: prod/.*
    kms: "arn:aws:kms:us-west-1:863191199317:alias/prod-encryption-key-c953aec"
